name: ct484_project
description: "Ứng dụng bán thuốc/dược phẩm"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: ^0.19.0
  carousel_slider: 5.0.0
  http: ^1.2.2
  shared_preferences: ^2.3.2
  flutter_dotenv: ^5.2.1
  pocketbase: ^0.18.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/drugs/
    - assets/diseases/
    - assets/cart/
    - assets/logos/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-Light.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-Regular.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-Medium.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-Bold.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-SemiBold.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-ExtraBold.ttf
